#! /bin/sh

#
# Copyright (C) 2008 Francesco Salvestrini
#                    Alessandro Massignan
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

TEST_FILENAME_IN1=./test-in1.txt
TEST_FILENAME_IN2=./test-in2.txt
TEST_FILENAME_OUT=./test-out.txt
TEST_FILENAME_EXP=./test-exp.txt

MERGESYMS_NEW="./mergesyms_new"

rm -f $TEST_FILENAME_IN1
rm -f $TEST_FILENAME_IN2
rm -f $TEST_FILENAME_OUT
rm -f $TEST_FILENAME_EXP

cat << EOF > $TEST_FILENAME_IN1
	SYMBOL1
	# This is a comment


	    # This is a comment
SYMBOL2
 SYMBOL3
	SYMBOL4 = 1
EOF

cat << EOF > $TEST_FILENAME_IN2

# This is a comment
  # This is another comment
	SYMBOL1                 =               aaaa

		SYMBOL2 = BBBBBBBBBBB1212
      # This is another comment
SYMBOL3 = 1
 SYMBOL4 =                                       0x1
EOF

cat << EOF > $TEST_FILENAME_EXP
This test must fail!
EOF

$MERGESYMS_NEW -i $TEST_FILENAME_IN1 \
	       -j $TEST_FILENAME_IN2 \
	       -o $TEST_FILENAME_OUT \
	       > /dev/null 2>&1 || exit 1

diff $TEST_FILENAME_OUT $TEST_FILENAME_EXP > /dev/null 2>&1 || exit 1

rm -f $TEST_FILENAME_IN1
rm -f $TEST_FILENAME_IN2
rm -f $TEST_FILENAME_OUT
rm -f $TEST_FILENAME_EXP

exit 0
