#
# Autogenerated file, DO NOT EDIT
#

#
# Files matching regexps:
#
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/Command.py
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/__init__.py
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/Trace.py
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/idlgen.in
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/Debug.py
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/Configuration.py
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/Exceptions.py
#  /home/francesco/Sviluppo/hybrid/hybrid/tools/serdes/src/Autoconfiguration.py
#

AC_DEFUN([PYTHON_AUTOFRISK_CHECKS],[
    AX_PROG_PYTHON_MODULES([warnings],[],[
        AC_MSG_ERROR([cannot find python module warnings])
    ])
    AX_PROG_PYTHON_MODULES([getopt],[],[
        AC_MSG_ERROR([cannot find python module getopt])
    ])
    AX_PROG_PYTHON_MODULES([exceptions],[],[
        AC_MSG_ERROR([cannot find python module exceptions])
    ])
    AX_PROG_PYTHON_MODULES([sys],[],[
        AC_MSG_ERROR([cannot find python module sys])
    ])
    AX_PROG_PYTHON_MODULES([traceback],[],[
        AC_MSG_ERROR([cannot find python module traceback])
    ])
    #AX_PROG_PYTHON_MODULES([Exceptions],[],[])
    AX_PROG_PYTHON_MODULES([os],[],[
        AC_MSG_ERROR([cannot find python module os])
    ])
    AX_PROG_PYTHON_MODULES([ConfigParser],[],[
        AC_MSG_ERROR([cannot find python module ConfigParser])
    ])
    #AX_PROG_PYTHON_MODULES([Trace],[],[])
    AX_PROG_PYTHON_MODULES([textwrap],[],[
        AC_MSG_ERROR([cannot find python module textwrap])
    ])
])

AC_DEFUN([PYTHON_AUTOFRISK_SUMMARY],[
])
