#!/bin/sh

#
# bootstrap
#
# Copyright (C) 2007, 2008 Francesco Salvestrini
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

#BASEDIR=utils

#. $BASEDIR/environment.sh || exit 1

PROGNAME=bootstrap

#
# Dump some useful informations
#
echo "$PROGNAME: Dumping build-tools information ..."
for tool in autoheader autoconf libtool libtoolize aclocal automake; do
    TOOLVER=`$tool --version | head -1`
    echo "$PROGNAME:   $TOOLVER"
done

#
# Remove files left from the previous run
#
echo "$PROGNAME: Removing autotools related files and directories ..."
rm -f  `find ./ -name "Makefile.in"`                 || exit 1
rm -f  config.cache aclocal.m4 config.h.in configure || exit 1
rm -f  config.guess config.sub ltmain.sh             || exit 1
rm -rf autom4te.cache                                || exit 1
rm -rf `find ./ -name ".deps"`                       || exit 1

#
# configure.ac
#
echo "$PROGNAME: Building configure.ac from configure.ac.in"
#if test ! -r ChangeLog ; then
#    echo "$PROGNAME: Cannot read ChangeLog file"
#    exit 1
#fi
#head -n 1 ChangeLog | sed -e 's/:.*//' > VERSION || {
#    echo "$PROGNAME: Cannot build VERSION file"
#    rm -f VERSION
#    exit 1
#}
rm -f configure.ac
VERSION=`git tag -l | sort -s -t '.' -k 1,1n -k 2,2n -k 3,3n | tail -n 1`
cat configure.ac.in | sed -e 's,[@]VERSION[@],'$VERSION',' > configure.ac || \
{ rm -f configure.ac ; exit 1 ; }
chmod a-w configure.ac

#
# src/config/Makefile.cfg
#
echo "$PROGNAME: Building src/config/Makefile.cfg ..."
OUTPUT_CFG=src/config/Makefile.cfg
INPUT_CFGS=`find ./ -name "rules.cfg"`

for i in $INPUT_CFGS ; do
    CURRENT=`echo $i | sed -e 's,./,$(top_srcdir)/,'`
    FILES="$FILES \\
$CURRENT"
done

rm -f $OUTPUT_CFG || exit 1
touch $OUTPUT_CFG || exit 1

cat > $OUTPUT_CFG <<EOF
##
## Include file for automake
##
## This file has been generated automatically, DO NOT EDIT!
##

CFG_FILES = $FILES

EOF

#
# src/*/Makefile.am generation from src/*/Makefile.am.in
#
for i in `find ./src -name "Makefile.inc.in"` ; do
    srcfile=$i
    dstfile=`dirname $i`/`basename $i .in`
    relativepath=`echo $i | sed -e 's,\.\/src/,,' | sed -e 's,/Makefile\.inc\.in,,'`

    #echo "$PROGNAME: Generating $dstfile from $srcfile ($relativepath)"
    #echo "$PROGNAME: Generating $dstfile ($relativepath)"
    echo "$PROGNAME: Generating $relativepath"

    #cat $srcfile | sed \
    #	-e "s,@subdir_srcdir@,$\(top_srcdir\)\/src/$relativepath,g" \
    #	-e "s,@subdir_builddir@,$\(top_builddir\)\/src/$relativepath,g" \
    #	> $dstfile
    #cat $srcfile | sed \
    #	-e "s,@subdir_srcdir@,$relativepath,g" \
    #	-e "s,@subdir_builddir@,$relativepath,g" \
    #	-e "s,@reldir@,$relativepath,g" \
    #	-e "s,@reldir@,$relativepath,g" \
    #	> $dstfile
    cat $srcfile | sed \
	-e "s,@reldir@,$relativepath,g" \
	> $dstfile || {
	echo "$PROGNAME: Cannot rearrange $srcfile into $dstfile"
	exit 1
    }
done

#
# autoreconf
#
echo "$PROGNAME: Handling autotools bootstrap ..."

echo "$PROGNAME: Running autoreconf ..."
aclocal    --force --install -I ./tools/autotools/m4 && \
autoreconf --verbose --force --install -Wall         || {
    exit 1
}

#
# bootstrap other packages
#
cd tools/choose && ./bootstrap || {
    echo "$PROGNAME: Cannot bootstrap tools/choose directory"
    exit 1
}

exit 0
