#!/bin/sh

#
# bootstrap
#
# Copyright (C) 2007, 2008 Francesco Salvestrini
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

#BASEDIR=utils

#. $BASEDIR/environment.sh || exit 1

PROGNAME=bootstrap

#
# Dump some useful informations
#
echo "$PROGNAME: Dumping tools information ..."
for tool in autoheader autoconf libtool libtoolize aclocal automake; do
    TOOLVER=`$tool --version | head -1`
    echo "$PROGNAME:   $TOOLVER"
done

#
# VERSION
#
echo "$PROGNAME: Building VERSION ..."
if test ! -r ChangeLog ; then
    echo "$PROGNAME: Cannot read ChangeLog file"
    exit 1
fi
head -n 1 ChangeLog | sed -e 's/:.*//' > VERSION || {
    echo "$PROGNAME: Cannot build VERSION file"
    rm -f VERSION
    exit 1
}

#
# autoreconf
#
echo "$PROGNAME: Handling autotools bootstrap ..."

echo "$PROGNAME: Running autoreconf ..."
aclocal    --force --install -I ./tools/autotools/m4 && \
autoreconf --verbose --force --install -Wall         || {
    exit 1
}

exit 0
